name: Main Branch Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Staging
        run: |
          # Add your staging deployment steps here
          echo "Deploying to staging..."
          
          # For demonstration purposes, you can replace this with your deployment command
          echo "Deployment command: deploy-to-staging"
    
  deploy-to-production:
    name: deployment
    needs: deploy
    runs-on: ubuntu-latest
    environment:
      name: permission
      url: 'http://www.myapp.com'
    steps:
      - name: deploy
        run: echo "I am deploying to the permission environment"
