name: example-workflow

on:
  push:
    branches:
      - main

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Bats
        run: npm install -g bats

    environment:
      name: permission
      url: ${{ steps.step_id.outputs.url_output }}
